---

- hosts: localhost
  user: node
  vars:
    custom_ssh_port: 33000
    JOB_PATH: "{{WORKSPACE}}"

  tasks:
  - name: ping all hosts
    ping:

  - local_action: command date '+%F-%H%M'
    register: release_timestamp

  - name: Git Checkout Frontend Repo
    git:
      repo: https://github.com/harishchanderdalal/ansible.git
      dest: "{{JOB_PATH}}/CHECKOUT{{release_timestamp.stdout}}"
      refspec: '+refs/pull/*:refs/heads/*'
      version: master

  - name: Build Frontend Deploy
    shell: |
      echo "Building PayUmoney Front End"
      exit 0

  - name: Create Build Tar
    archive:
      path: "{{JOB_PATH}}/CHECKOUT{{release_timestamp.stdout}}"
      format: zip
