---
# tasks file for common

- name: include OS related var files
  include_vars: "{{ ansible_os_family }}_vars.yml"

- name: include OS sepcific common tasks
  include: "{{ ansible_os_family }}_setup.yml"